version: '3.7'

services:
  discord-bot:
    user: ${DOCKER_USER}:${DOCKER_GROUP}
    build:
      user: ${DOCKER_USER}:${DOCKER_GROUP}
      target: build-env
      context: ${WORKDIR}
      args:
        WORKDIR: ${WORKDIR}
    ports:
      - "43106:43106" # Debug port
    volumes:
      - ${HOME}/go:/go
      - ${WORKDIR}/.volumes/cache:/.cache
      - ${WORKDIR}:${WORKDIR}
#       - ${WORKDIR}/.env:${WORKDIR}/cmd/trash/.env
    command: /dlv debug --continue --headless --listen=:43106 --api-version=2 --accept-multiclient --build-flags='-buildvcs=false'
    env_file:
      - .env
    working_dir: ${WORKDIR}/cmd/trash
